# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b399c7dd32038b4e92c7c7199fd8e25ce72db98cbcb8d14cecd8fa38f2de08155f68c722608a12d3129322390b515b086ec59de35123509849e9e04e41657ee0

test:
  secret_key_base: 412b6abef32cb1d5d8cd1d43eba4f990a251cb78ccb3f95de01948d7dcd25997b674e4af073a1c1ce1c1bd451d567ee167371e7c522f42e73ef5544216344838

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
