source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'bcrypt', '~> 3.1.7'

gem 'puma'
gem 'faker'
gem 'rails_12factor', group: :production

gem 'kaminari'
gem 'bootstrap-sass'

gem 'figaro'
gem 'mandrill_dm'

gem 'react-rails'

group :development, :test do
  gem 'pry'
  gem 'minitest'
  gem 'shoulda', '~> 3.5'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
